name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@1.0.0
        with:
           username: "mozayed"
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           image_path: "./assets/thm_propic.png"
           committer_username: "thm-p4p1-bot"
           committer_email: "p4p1@thm.bot"
           commit_message: "Updated THM profile badge"
