name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: mozayed007/MoZayed007@main
        with:       
          CREDLY_USER: mohamedz.ahmed # optional, but default will use the same from githubmohamedz.ahmed
